name: Code Coverage

on: [push]

jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.13  # Replace '3.x' with your desired Python version

      - name: Install dependencies
        run: |
          pip install pytest-cov pytest
          pip install -r requirements.txt
          echo requirements installed
      - name: Run the tests
        run: |
          cd tests
          coverage run --source=test -m pytest test_*.py
          coverage xml -i
      - name: Upload coverage report to Codecov
        run: |
          bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
